### ISSUE TITLE
List multiple servers in voluri

### ISSUE THREAD

**Issue by AmeerGN** [sapk/docker-volume-gluster#11]
Is it possible to add multiple volume servers (peers) ? for example:
```
volumes:
  some_vol:
    driver: sapk/plugin-gluster
    driver_opts:
      voluri: "gluster1.com:glustervol1,gluster2.com:glustervol1"
```
