### ISSUE TITLE
Gluster Volume per Container or Shared Gluster Volume

### ISSUE THREAD

**Issue by Vad1mo** [sapk/docker-volume-gluster#14]
I manually created a gluster volume `gv0`.  Now I had the expectation that when use the plugin, I can use this single gluster volume `gv0` for multiple container. 

I guess It is not intended to be used in this way, (or I can't find an alternative), because the data are stored in the root folder of the gluster volume `gv0/`. I was actually expecting them in `gv0/portainer-data/...` 

So is it intended that each container should have its own gluster volume? 

```
volumes:
  portainer-data:
    driver: glusterfs
    driver_opts:
      voluri: "localhost:gv0"
```
