### ISSUE TITLE
Is it supposed to automatically create the specified subdir?

### ISSUE THREAD

**Issue by criverapr** [sapk/docker-volume-gluster#59]
I was trying this tutorial: https://sysadmins.co.za/container-persistent-storage-for-docker-swarm-using-a-glusterfs-volume-plugin/

My GlusterFS version is 3.13.2.  I'm not sure if it is just a permissions issue, but when I try this in my compose file:
```
volumes:
  vol1:
    driver: glusterfs
    name: "gfs/vol1"
```

The container doesn't have the gluster mount, but if I do the following:
```
volumes:
  vol1:
    driver: glusterfs
    name: "gfs"
```

It works fine, but the data is put into the root of the volume.  The first option works fine if I create the "vol1" directory before running the stack, and this is why I think it may just be a permissions issue.  What should be the permissions set at the filesystem level on the gluster volume mount?
